### ISSUE TITLE
Domain masked by PHP internal server use

### ISSUE THREAD

**Issue by andybee** [stackery/php-lambda-layer#13]
If you try and call `$SERVER['HTTP_HOST']` to derive the requested host when running the Lambda function behind API Gateway or an Application Load Balancer, you receive `localhost` rather than the originating request's Host.

I presume this is because internally we're calling PHP's development HTTP server with a `http://localhost/` URL.

This sort of comes back to a question in #11 about where the aim of the project lies in terms of PHP support in Lambda. If we aim to simulate an HTTP-driven hosting environment, we should fix this. If we're merely seeking to execute "any" PHP script in a Lambda fashion, then this doesn't necessarily need fixing. But then we should probably seek to expose the event object etc.?

I've presumed from the approach of writing HTTP headers etc. back out in the response, we're aiming for the HTTP-like execution of PHP within the function.

**Comment by txase** [comment]
@andybee Yes, ideally we should be setting `$SERVER['HTTP_HOST']` correctly. But API Gateway doesn't actually provide the hostname information in the events it invokes the functions with. You can find the event structure here:

https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format

I don't think there's anything we can reasonably use to populate this value with. I'm going to close the issue as it's unfixable. Please re-open if you think there's something we can do.

**Comment by andybee** [comment]
Why not the Host header value of the incoming request?

If it’s reached the function, it can be deemed “good”, and it helps with “this-CNAMEs-that-CNAMEs-this” type setups when you’ve got a custom domain on top of Cloudfront hitting an origin ALB with a custom domain for HTTPS which hits Lambda.

**Comment by txase** [comment]
Oh, you're right! I hadn't thought about that header :).

I'll reopen the issue. Now we need to figure out how to set that value correctly. Unfortunately, I'm not sure how to do that off the top of my head.

**Comment by andybee** [comment]
Well, this is the confusing thing. The way to do it would be to simply tack it on the headers of the request being sent to the internal dev server.

But from what I can tell, that's exactly what's occurring in `bootstrap` already - it feeds the headers from the incoming Gateway/ALB event in to the headers sent with the request to the internal server.

**Comment by andybee** [comment]
As a rough example, if I create a script:

```
echo $_SERVER['HTTP_HOST'];
```

And then run it locally:

```
$ php -S 0:8080 test.php
```

And then cURL it:

```
$ curl -H "Host: test" http://localhost:8080/blah
```

I get:

`test` as the output.

**Comment by txase** [comment]
Oh yeah, that sounds like it could work :). Would you be able to test out a PR to do that?

**Comment by andybee** [comment]
Apologies, this must be application specific. I've done a simplified test behind CloudFront and ALB and the originating host is reaching PHP.

We're seeing a weird issue when POST and/or cookies are used which seems to change the `Host` to `localhost` and then ALB rejects the request with a gateway error, presumably (though, unproven at this stage) because the `Host` value doesn't match.
