### ISSUE TITLE
$_POST not populated on HTTP POST

### ISSUE THREAD

**Issue by martysweet** [stackery/php-lambda-layer#14]
I've noticed that `$_POST` is not populated when sending fields (using HTTP POST) to a simple function given the sample template.

Related to #13, what is the specific aim of this project? If we are aiming to provide a fully functioning web-server, then this should be supported. If not, then this perhaps should be down to the implementing developer to expect some payload and parse it appropriately.

For example, developers from a REST background would expect a JSON body within a POST, but some PHP apps use `application/x-www-form-urlencoded` via HTML forms. 

I see in `bootstrap` the body of the request is being sent to the PHP webserver, however, I can't see it with `var_dump(file_get_contents('php://input'));` - Any Ideas? We could then provide a snippet of processing for JSON or Form Data.

**Comment by txase** [comment]
The aim of this runtime is to act like a PHP web server, receiving HTTP requests and responding with HTTP responses as the PHP development web server does. This means `$_POST` should be supported.

I'm not sure why `$_POST` isn't being set properly. I found this comment in the documentation that may be related: http://php.net/manual/en/reserved.variables.post.php#114598. What content-type value are you sending?

**Comment by martysweet** [comment]
Great thanks for the clarification. I am currently sending something like this:

```
POST /Prod/index.php HTTP/1.1
Host: apigatewayhost
User-Agent: insomnia/5.16.6
Content-Type: application/x-www-form-urlencoded
Accept: */*
Content-Length: 47
example=saduuiuhhu&form2=dsadsadsadasdsadsadsad
```
yet the `php://input` and `$_POST` are empty. I can confirm the content type is being passed to the PHP server ` ["CONTENT_TYPE"]=> string(33) "application/x-www-form-urlencoded" ["HTTP_CONTENT_TYPE"]=> string(33) "application/x-www-form-urlencoded"`

If the intention is to support such functionality I will look at getting to the bottom of this tomorrow and submit a PR (hopefully :smile:).

**Comment by txase** [comment]
Maybe we're somehow not sending the body in correctly when making the curl request to the PHP webserver. That's where I would start poking.

**Comment by atrope** [comment]
@martysweet 
can you try using this layer?

`arn:aws:lambda:us-east-1:272581579102:layer:php71:107
` 

Here POST is working. If it does not, put here the dumps of cloudwatch.

**Comment by martysweet** [comment]
Hi @atrope, that works a treat! Looks like there are quite a few changes in that layer, are you looking at merging them? 

Is there anything else you would like me to test?

**Comment by atrope** [comment]
@martysweet I've changed a lot and i don't think it would be an easy PR.
I Changed now to use php-cgi based on barryvdh code.

You can check it here:
https://github.com/SuaMusica/php-lambda-layer/blob/master/bootstrap
This is the build(I Also install phalcon but you can remove should you want):
https://github.com/SuaMusica/php-lambda-layer/blob/master/build.sh

If you want you can try the layer here:
`arn:aws:lambda:us-east-1:272581579102:layer:php71:152
`

You can also if you want try to debug it and find more bugs as i am now working on the one I described in #11 

Maybe after I finnish and i don't find any other bugs we could talk on making a PR and changing the base php-cli for php-cgi
