### ISSUE TITLE
Application load balancer requests

### ISSUE THREAD

**Issue by gszeszko** [stackery/php-lambda-layer#19]
Is version 5 of the layer expected to handle requests reaching lambda via the ALB?  I keep getting 502 for such attempts.  Cloud trail records a request but it appears that the error is generated in the layer, even before it reaches my application code.  When I use application gateway, the request is making it all the way into the lambda function.

**Comment by txase** [comment]
In theory it should work, but I have not personally verified the functionality. It was contributed in this PR: #5.

Can you provide more details on the error you are seeing? What is the message input into the function, and what is the response? You can debug the bootstrap file by copying it into your function code at the root of the code package in case you need to add any logging to identify the issue.

**Comment by gszeszko** [comment]
Sorry, I ran out of time before I could test it today.  I will give it a try tomorrow.
How do I debug the bootstrap file?  I missing that reference.  Where do I find the "bootstrap" file?

**Comment by txase** [comment]
If there is an issue with the layer, it is probably in the `bootstrap` file. This is the file literally named "bootstrap" at the root of this repo.

The bootstrap file from this layer is executed when the Lambda function is invoked. But if you include a file named "bootstrap" in your function, it takes precedence.

So, to debug the "bootstrap" file of this layer, you can copy it into your function. Then, you can make any changes you want to debug and fix the issue.

**Comment by gszeszko** [comment]
I see.  The bootstrap file is interesting.  How do I log from it to the cloudwatch stream?  Is there a function to call or is there a different way of echoing logs there?

**Comment by txase** [comment]
Whatever you print in PHP (to stdout or stderr) will end up in the cloudwatch logs. So you can simply call `print("Hello World");` and that will be logged.

**Comment by gszeszko** [comment]
That's easy enough.
I can see that ALB initiated calls get into my app layer. I am seeing some
logs that my app generates. But the return call is still 502 with html
content type, which is not generated by my app. I have crash and error
handlers and they are not hit. Which makes me think that the embedded web
server is not happy about something.
I will look into this some more next week and wull add pribt statements to
the bootstrap if necessary.

**Comment by gszeszko** [comment]
ALB routing works fine.  The problem was permissions between the ALB and lambda.
