### ISSUE TITLE
Adding custom extensions

### ISSUE THREAD

**Issue by colinpizarek** [stackery/php-lambda-layer#3]
I'm trying to add my own custom extensions. For example, I'm trying to add PDO. I've created a layer using this file:
[extensions-layer-1.zip](https://github.com/stackery/php-lambda-layer/files/2636469/extensions-layer-1.zip)

I've added
`extension=pdo.so`
to my php.ini file.

I'm loading the PDO extension layer after the PHP layer, but it's not showing up when I dump the list of enabled extensions.

I have no idea how to use your specified Docker image to build a php extension correctly, so I nabbed the pdo.so file from an EC2 instance I spun up. I suspect this is probably the problem, but I'm not sure where to go from here. Suggestions?

**Comment by txase** [comment]
We released a new layer version (4) this morning to address some extension/php.ini issues. Which layer version are you using?

**Comment by txase** [comment]
Nevermind, we fixed those issues for you :). Let me think some more about this issue.

**Comment by txase** [comment]
What do you see in the logs in CloudWatch?

**Comment by colinpizarek** [comment]
```
[Sun Dec 2 01:29:53 2018] PHP Warning: PHP Startup: Unable to load dynamic library '/opt/lib/php/7.1/modules/pdo.so' - /opt/lib/php/7.1/modules/pdo.so: undefined symbol: zend_empty_string in Unknown on line 0
```

Looks like it cannot find the extension that's supposed to be loaded by my layer.

**Comment by colinpizarek** [comment]
I've tried adjusting the merge order and executing the PDO layer both before and after the PHP layer. Same result both ways.

**Comment by txase** [comment]
Sounds like you need another .so that would contain zend_empty_string. It might be available in a zend rpm package in the lambci docker image.

**Comment by txase** [comment]
I’m going to close this issue as it appears the php layer is operating correctly. If you find there’s something wrong with the layer itself feel free to reopen.
