### ISSUE TITLE
Missing Authentication Token

### ISSUE THREAD

**Issue by kaihendry** [stackery/php-lambda-layer#31]
Following your guide, when I goto the end point in 
https://ap-southeast-1.console.aws.amazon.com/lambda/home?region=ap-southeast-1#/applications/sam-app

https://rv1gzylepi.execute-api.ap-southeast-1.amazonaws.com/Prod I get `{"message":"Missing Authentication Token"}`

Only when I complete the URL with index.php, it works:
https://rv1gzylepi.execute-api.ap-southeast-1.amazonaws.com/Prod/index.php

I googled around and found this related issue: https://github.com/awslabs/aws-sam-cli/issues/437#issuecomment-479735833

**Comment by txase** [comment]
Hi @kaihendry!

This is a limitation of how AWS API Gateway works. If you go to the api endpoint without at least `/` after the stage name (`Prod` in your case), you will get the missing authentication token message. As soon as you add `/` to the end it should work.

If you map your API to a custom domain this issue goes away. If it's mapped to example.com, you would be able to hit `https://example.com` and it would correctly render the root route.

I'm going to close this issue out as it's unrelated to the PHP runtime.
