### ISSUE TITLE
Include bcmath extension

### ISSUE THREAD

**Issue by KorvinSzanto** [stackery/php-lambda-layer#32]
BCMath is typically enabled when compiling PHP: https://www.php.net/manual/en/bc.installation.php

But it's disabled in this layer. What's the best way to include this extension?

**Comment by txase** [comment]
Hi @KorvinSzanto!

My goal is to keep this runtime layer as lean as reasonably possible. We have added additional extensions to it when they are clearly available by default.

But alternatively, you can build the extension and put it in a layer. Here's a quote from the Readme on how to do it:

> Extensions can be built using the lambci/lambda:build-nodejs8.10 Docker image. It is recommended that custom extensions be provided by a separate Lambda Layer with the extension .so files placed in /lib/php/${PHP_VERSION}/modules/ so they can be loaded alongside the built-in extensions listed above.

I'm going to close this issue out, but please re-open if creating your own layer isn't working or if you feel bcmath should be included in the base layer.

Thanks!

**Comment by KorvinSzanto** [comment]
@txase, I don't believe it's possible to compile and include BCMath separately, see the link in my original post. In order to enable bcmath you must compile PHP with the proper flag enabled.
