### ISSUE TITLE
mysqli extension not loading

### ISSUE THREAD

**Issue by daveatpeta** [stackery/php-lambda-layer#37]
I'm using version 7.3 and tried adding mysqli.so extension to php.ini, but it simply won't load.
On the other hand, pdo_mysql.so is loading correctly.

Any idea what may be wrong?

Regards,

**Comment by daveatpeta** [comment]
Figured it out. Sorry.

Extensions have to be loaded in this order (not the order on the README file of this project).

extension=mysqlnd.so
extension=mysqli.so

**Comment by eli007s** [comment]
how do you load extensions. where do you make those changes?

**Comment by txase** [comment]
@eli007s You add a php.ini file to the root of your Lambda function source code with extension declarations like @daveatpeta suggested.

Thanks!

**Comment by security-intel** [comment]
> Figured it out. Sorry.
> 
> Extensions have to be loaded in this order (not the order on the README file of this project).
> 
> extension=mysqlnd.so
> extension=mysqli.so

Life saver!
