### ISSUE TITLE
Is this suitable for production?

### ISSUE THREAD

**Issue by epicfaace** [stackery/php-lambda-layer#45]
Going to the docs (https://php.net/manual/en/features.commandline.webserver.php) I see:

> Warning
This web server was designed to aid application development. It may also be useful for testing purposes or for application demonstrations that are run in controlled environments. It is not intended to be a full-featured web server. It should not be used on a public network.

So, given this, is using this php-lambda-layer suitable for production? Or is it better to use another web server instead?

**Comment by txase** [comment]
There are many possible reasons the built-in web server, which this runtime uses, may be considered unsuitable for production. For example, the web server is single-threaded, and thus can only handle one request at a time. That's not a problem for serverless usage; any given Lambda Function will only be handling one request during an invocation.

There may be other reasons it is unsuitable for production, but the docs don't enumerate them. I did a search once, and didn't find any other reasons it shouldn't be used in production (and some people do use it there anyways).

In the end, this runtime layer uses software that has been labeled as not production-ready, but that may or may not be valid for this use case. We can't modify this label. It's up to you to decide whether this is a concern that prevents usage of this layer.

**Comment by epicfaace** [comment]
Ok, thanks!
