### ISSUE TITLE
gd, jpeg, png and webp? Maybe even ImageMagick?

### ISSUE THREAD

**Issue by treii28** [stackery/php-lambda-layer#46]
I was hoping to use PHP for generating thumbnails of images stored in s3 buckets. Why no support for any graphics tools?

**Comment by txase** [comment]
You can add extensions to your function, which I recommend doing by building the extensions using lambci and zipping them into a Lambda Layer. This is described at the bottom of the extensions section of the readme: https://github.com/stackery/php-lambda-layer#extensions.

Thanks!
