### ISSUE TITLE
You are not authorized to perform: lambda:GetLayerVersion.

### ISSUE THREAD

**Issue by grundyweb** [stackery/php-lambda-layer#50]
Thanks guys for some excellent work on this layer, however when trying to add the ARN in AWS Lambda in the following region:

`arn:aws:lambda:eu-north-1:887080169480:layer:php73:3 `

and save the changes, I get the following error:
_You are not authorized to perform: lambda:GetLayerVersion._

I'm assuming this is because the layer isn't published in _eu-north-1_. Would it be possible to simply add _eu-north-1_ to the list of regions in **regions.sh**?

**Comment by txase** [comment]
Hi @grundyweb!

You're right that we hadn't published a layer to eu-north-1 yet. I just published a layer (version 3) to the region. I also updated the regions.sh file in the development branch, which will be used the next time we release a new layer version.

Thanks!
