### ISSUE TITLE
error using simplexml_load_string

### ISSUE THREAD

**Issue by warrence** [stackery/php-lambda-layer#63]
Hi, im getting error 
`Call to undefined function App\Http\Controllers\simplexml_load_string()`

i have enable the below in php.ini

```
extension=simplexml.so
extension=xml.so
extension=xmlreader.so
extension=xmlwriter.so
```

But im still getting the error, any advise?

Thanks for this great layer!

**Comment by theoziran** [comment]
@warrence try to import the function `use function simplexml_load_string;` or call it as `\simplexml_load_string`.

I think it is not related to issues in the php.init.

**Comment by warrence** [comment]
It works when in my local machine using 
`php -S localhost:8000 -t public`

i tried `\simplexml_load_string` and `use function simplexml_load_string;` both are giving the same error.

**Comment by warrence** [comment]
Hi, it works now, i did not realize that im using a forked version, after i change to the parent version it works well. Thanks
