### ISSUE TITLE
README on master refers to deployed version of layer which does not contain referenced functionality

### ISSUE THREAD

**Issue by andybee** [stackery/php-lambda-layer#9]
Just a quick heads up, because the README on master has been updated to talk about the ALB functionality and config changes, but still refers to version 4 of the built/deployed layer. There's a mismatch between "current" and "future" functionality.

Might be better to prepare the documentation on a branch until it's deployed to AWS, so there's no confusion?

**Comment by txase** [comment]
You caught me :). I wondered how long I could get away without separate development/master branches, and it turns out it was only 1 day!

I'll get this fixed up. Thanks for filing an issue.

**Comment by andybee** [comment]
Not a problem. We're actively developing against this work and hoping to contribute a few bits soon. We had until quite recently rolled our own solution for PHP in Lambda, but Layers is making it significantly more refined so keen to double down on this project.

**Comment by txase** [comment]
I both released what was in master as layer version 5 and created a separate development branch for new work. I added a PR template telling people to open new PRs against the development branch.

🙏
